/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class ValidateSAid {
public static boolean  isValid(String idnumber) {
    //basic validation
    
    
}
}
