/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testValidIdNumbers() {
        assertTrue(ValidateSAid.isValid("2001014800086"));
        assertTrue(ValidateSAid.isValid("2909035800085"));
    }
    
    private void assertTrue(boolean valid) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'assertTrue'");
    }

}
