/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertFalse;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testValidIdNumbers() {
        assertTrue(ValidateSAid.isValid("2001014800086"));
        assertTrue(ValidateSAid.isValid("2909035800085"));
    }
    
    private void assertTrue(boolean valid) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'assertTrue'");
    }
@Test
    void testInvalidLength() {
        assertFalse(ValidateSAid.isValid("123"));
        assertFalse(ValidateSAid.isValid("2001014800086123"));
    }
    @Test
    void testNonNumeric() {
        assertFalse(ValidateSAid.isValid("20010A4800086"));
        assertFalse(ValidateSAid.isValid("abcdefghijklm"));
    }
    @Test
    void testLuhnAlgorithm() {
        assertTrue(ValidateSAid.isValid("2001014800086"));  // Valid
        assertFalse(ValidateSAid.isValid("2001014800087")); // Invalid
    }
    @Test
    void testDateValidation() {
        assertTrue(ValidateSAid.isValid("9202204800086"));  // Valid date
        assertTrue(ValidateSAid.isValid("0002294800082"));  // Leap year
        assertFalse(ValidateSAid.isValid("9902304800083")); // Invalid day
        assertFalse(ValidateSAid.isValid("9913024800081")); // Invalid month
    }
    @Test
    void testCitizenshipDigit() {
        assertTrue(ValidateSAid.isValid("9202204800086"));  // Citizen (0)
        assertTrue(ValidateSAid.isValid("9202204800183"));  // Resident (1)
        assertFalse(ValidateSAid.isValid("9202204800280")); // Invalid (2)
    }
}
