/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertFalse;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testValidIdNumbers() {
        assertTrue(ValidateSAid.isValid("2001014800086"));
        assertTrue(ValidateSAid.isValid("2909035800085"));
    }
    
    private void assertTrue(boolean valid) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'assertTrue'");
    }
@Test
    void testInvalidLength() {
        assertFalse(ValidateSAid.isValid("123"));
        assertFalse(ValidateSAid.isValid("2001014800086123"));
    }
    @Test
    void testNonNumeric() {
        assertFalse(ValidateSAid.isValid("20010A4800086"));
        assertFalse(ValidateSAid.isValid("abcdefghijklm"));
    }
    @Test
    void testLuhnAlgorithm() {
        assertTrue(ValidateSaid.isValid("2001014800086"));  // Valid
        assertFalse(ValidateSaid.isValid("2001014800087")); // Invalid
    }
}
